### ISSUE TITLE
Fix GitHub integration

### ISSUE THREAD

**Issue by itsrachelfish** [wetfish/fishy-bot#59]
Something changed with the way webhooks are sent from GitHub. Ever since, fishy has been unable to verify requests coming from GitHub. As a result, the module has been disabled for a few months now

**Comment by Meleeman01** [comment]
Ive tried to replicate this on my instance but i got the webhook to work with minimal problems, as long as fishy is in the room and is on the right port number using application/json setting in the webhook and listen for everything also set in teh project webhook, it should work. I was using nodejs v6.x.x enviornment. in the startup of bot.js i noticed a message that warned about event listeners and that it maxed out at 11, and that there may be a memory leak in fishy.

`(node:19161) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
(node:19161) Warning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
`

**Comment by itsrachelfish** [comment]
Umm, I guess this is fixed now?
